services:
  apisix:
    image: apache/apisix:3.15.0-debian
    container_name: apisix-standalone
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 9080:9080
      - 9090:9090
      - 9180:9180
    volumes:
      - ./apisix/plugins/:/opt/custom-plugins/apisix/plugins/
      - ./conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    environment:
      - APISIX_STAND_ALONE=true
    networks:
      - apisix_network

  openresty:
    image: openresty/openresty:alpine
    container_name: openresty-servcie
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    networks:
      - apisix_network

networks:
  apisix_network:
    driver: bridge
