services:
  openresty:
    image: openresty/openresty:alpine
    container_name: openresty-servcie
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    networks:
      - apisix_network

networks:
  apisix_network:
    driver: bridge
