worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        location = /client {
            default_type text/plain;
            content_by_lua_block {
                local client = ngx.req.get_headers()["x-client"]
                if client == "smile" then
                    ngx.status = ngx.HTTP_OK
                    ngx.say("success")
                else
                    ngx.status = ngx.HTTP_UNAUTHORIZED
                    ngx.say("not allowed")
                end
            }
        }

        location / {
            return 404 "not found";
        }
    }
}
